package enum

import (
	"fmt"
	"io"
	"strconv"
)

var ConnectiveKey = "connective"

type Connective string

// Please do not edit this file, consider making a new one with appending _edit in the namefile
// This file will be automatically regenerated by bendt-generator
// Changes in this File may be unsaved or replaced when regenerated

const (
	ConnectiveAnd Connective = "AND"
	ConnectiveOr  Connective = "OR"
)

var AllConnective = []Connective{
	ConnectiveAnd,
	ConnectiveOr,
}

func (e Connective) IsValid() bool {
	switch e {
	case ConnectiveAnd, ConnectiveOr:
		return true
	}
	return false
}

func (e Connective) String() string {
	return string(e)
}

func (e *Connective) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Connective(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Connective", str)
	}
	return nil
}

func (e Connective) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
